namespace: amazon
name: cloud
version: 0.4.0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license_file: LICENSE
tags:
  - amazon
  - cloud
  - aws
dependencies:
  amazon.aws: '>=5.3.0'
  community.aws: '>=5.3.0'
repository: https://github.com/ansible-collections/amazon.cloud
documentation: https://github.com/ansible-collections/amazon.cloud/tree/main/docs
homepage: https://github.com/ansible-collections/amazon.cloud
issues: https://github.com/ansible-collections/amazon.cloud/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
  - '*cloud-config-aws.ini'
  - '*cloud-config-aws.yml'
  - changelogs/.plugin-cache.yaml
  - config/*
