# SonarCloud project configuration for amazon.cloud
# Complete documentation: https://docs.sonarqube.org/latest/analysis/analysis-parameters/

# Must match SonarCloud project key exactly (Analyze new project in UI).
sonar.projectKey=ansible-collections_amazon.cloud
sonar.organization=ansible-collections

sonar.sources=.
sonar.projectName=amazon.cloud

sonar.python.coverage.reportPaths=coverage.xml

sonar.tests=tests/unit,tests/integration
sonar.python.version=3.9
sonar.newCode.referenceBranch=main

sonar.exclusions=tests/**,.tox/**
