#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2022, Ansible Project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# template: header.j2
# This module is autogenerated by amazon_cloud_code_generator.
# See: https://github.com/ansible-collections/amazon_cloud_code_generator

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
module: cloudtrail_event_data_store
short_description: Creates and manages a new event data store
description:
- Creates and manages Creates a new event data store.a new event data store.
options:
    advanced_event_selectors:
        description:
        - Advanced event selectors let you create fine-grained selectors for the following
            AWS CloudTrail event record ?elds.
        - They help you control costs by logging only those events that are important
            to you.
        elements: dict
        suboptions:
            field_selectors:
                description:
                - A single selector statement in an advanced event selector.
                elements: dict
                suboptions:
                    ends_with:
                        description:
                        - An operator that includes events that match the last few
                            characters of the event record field specified as the
                            value of Field.
                        elements: str
                        type: list
                    equals:
                        description:
                        - An operator that includes events that match the exact value
                            of the event record field specified as the value of Field.
                        - This is the only valid operator that you can use with the
                            readOnly, eventCategory, and resources.type fields.
                        elements: str
                        type: list
                    field:
                        description:
                        - A field in an event record on which to filter events to
                            be logged.
                        - Supported fields include readOnly, eventCategory, eventSource
                            (for management events), eventName, resources.type, and
                            resources.ARN.
                        type: str
                    not_ends_with:
                        description:
                        - An operator that excludes events that match the last few
                            characters of the event record field specified as the
                            value of Field.
                        elements: str
                        type: list
                    not_equals:
                        description:
                        - An operator that excludes events that match the exact value
                            of the event record field specified as the value of Field.
                        elements: str
                        type: list
                    not_starts_with:
                        description:
                        - An operator that excludes events that match the first few
                            characters of the event record field specified as the
                            value of Field.
                        elements: str
                        type: list
                    starts_with:
                        description:
                        - An operator that includes events that match the first few
                            characters of the event record field specified as the
                            value of Field.
                        elements: str
                        type: list
                type: list
            name:
                description:
                - An optional, descriptive name for an advanced event selector, such
                    as Log data events for only two S3 buckets.
                type: str
        type: list
    event_data_store_arn:
        description:
        - The ARN of the event data store.
        type: str
    force:
        default: false
        description:
        - Cancel IN_PROGRESS and PENDING resource requestes.
        - Because you can only perform a single operation on a given resource at a
            time, there might be cases where you need to cancel the current resource
            operation to make the resource available so that another operation may
            be performed on it.
        type: bool
    multi_region_enabled:
        description:
        - Indicates whether the event data store includes events from all regions,
            or only from the region in which it was created.
        type: bool
    name:
        description:
        - The name of the event data store.
        type: str
    organization_enabled:
        description:
        - Indicates that an event data store is collecting logged events for an organization.
        type: bool
    purge_tags:
        default: true
        description:
        - Remove tags not listed in I(tags).
        type: bool
    retention_period:
        description:
        - The retention period, in days.
        type: int
    state:
        choices:
        - present
        - absent
        - list
        - describe
        - get
        default: present
        description:
        - Goal state for resource.
        - I(state=present) creates the resource if it doesn't exist, or updates to
            the provided state if the resource already exists.
        - I(state=absent) ensures an existing instance is deleted.
        - I(state=list) get all the existing resources.
        - I(state=describe) or I(state=get) retrieves information on an existing resource.
        type: str
    tags:
        aliases:
        - resource_tags
        description:
        - A dict of tags to apply to the resource.
        - To remove all tags set I(tags={}) and I(purge_tags=true).
        type: dict
    termination_protection_enabled:
        description:
        - Indicates whether the event data store is protected from termination.
        type: bool
    wait:
        default: false
        description:
        - Wait for operation to complete before returning.
        type: bool
    wait_timeout:
        default: 320
        description:
        - How many seconds to wait for an operation to complete before timing out.
        type: int
author: Ansible Cloud Team (@ansible-collections)
version_added: 0.2.0
requirements: []
extends_documentation_fragment:
- amazon.aws.aws
- amazon.aws.ec2
"""

EXAMPLES = r"""
"""

RETURN = r"""
result:
    description:
        - When I(state=list), it is a list containing dictionaries of resource information.
        - Otherwise, it is a dictionary of resource information.
        - When I(state=absent), it is an empty dictionary.
    returned: always
    type: complex
    contains:
        identifier:
            description: The unique identifier of the resource.
            type: str
        properties:
            description: The resource properties.
            type: dict
"""

import json

from ansible_collections.amazon.aws.plugins.module_utils.core import AnsibleAWSModule
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    CloudControlResource,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    snake_dict_to_camel_dict,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    ansible_dict_to_boto3_tag_list,
)


def main():

    argument_spec = dict(
        state=dict(
            type="str",
            choices=["present", "absent", "list", "describe", "get"],
            default="present",
        ),
    )

    argument_spec["advanced_event_selectors"] = {
        "type": "list",
        "elements": "dict",
        "options": {
            "name": {"type": "str"},
            "field_selectors": {
                "type": "list",
                "elements": "dict",
                "options": {
                    "field": {"type": "str"},
                    "equals": {"type": "list", "elements": "str"},
                    "starts_with": {"type": "list", "elements": "str"},
                    "ends_with": {"type": "list", "elements": "str"},
                    "not_equals": {"type": "list", "elements": "str"},
                    "not_starts_with": {"type": "list", "elements": "str"},
                    "not_ends_with": {"type": "list", "elements": "str"},
                },
            },
        },
    }
    argument_spec["event_data_store_arn"] = {"type": "str"}
    argument_spec["multi_region_enabled"] = {"type": "bool"}
    argument_spec["name"] = {"type": "str"}
    argument_spec["organization_enabled"] = {"type": "bool"}
    argument_spec["retention_period"] = {"type": "int"}
    argument_spec["termination_protection_enabled"] = {"type": "bool"}
    argument_spec["tags"] = {"type": "dict", "aliases": ["resource_tags"]}
    argument_spec["state"] = {
        "type": "str",
        "choices": ["present", "absent", "list", "describe", "get"],
        "default": "present",
    }
    argument_spec["wait"] = {"type": "bool", "default": False}
    argument_spec["wait_timeout"] = {"type": "int", "default": 320}
    argument_spec["force"] = {"type": "bool", "default": False}
    argument_spec["purge_tags"] = {"type": "bool", "default": True}

    required_if = [
        ["state", "present", ["event_data_store_arn"], True],
        ["state", "absent", ["event_data_store_arn"], True],
        ["state", "get", ["event_data_store_arn"], True],
    ]
    mutually_exclusive = []

    module = AnsibleAWSModule(
        argument_spec=argument_spec,
        required_if=required_if,
        mutually_exclusive=mutually_exclusive,
        supports_check_mode=True,
    )
    cloud = CloudControlResource(module)

    type_name = "AWS::CloudTrail::EventDataStore"

    params = {}

    params["advanced_event_selectors"] = module.params.get("advanced_event_selectors")
    params["event_data_store_arn"] = module.params.get("event_data_store_arn")
    params["multi_region_enabled"] = module.params.get("multi_region_enabled")
    params["name"] = module.params.get("name")
    params["organization_enabled"] = module.params.get("organization_enabled")
    params["retention_period"] = module.params.get("retention_period")
    params["tags"] = module.params.get("tags")
    params["termination_protection_enabled"] = module.params.get(
        "termination_protection_enabled"
    )

    # The DesiredState we pass to AWS must be a JSONArray of non-null values
    _params_to_set = {k: v for k, v in params.items() if v is not None}

    # Only if resource is taggable
    if module.params.get("tags") is not None:
        _params_to_set["tags"] = ansible_dict_to_boto3_tag_list(module.params["tags"])

    params_to_set = snake_dict_to_camel_dict(_params_to_set, capitalize_first=True)

    # Ignore createOnlyProperties that can be set only during resource creation
    create_only_params = {}

    # Necessary to handle when module does not support all the states
    handlers = ["create", "read", "update", "delete", "list"]

    state = module.params.get("state")
    identifier = ["event_data_store_arn"]

    results = {"changed": False, "result": {}}

    if state == "list":
        if "list" not in handlers:
            module.exit_json(
                **results, msg=f"Resource type {type_name} cannot be listed."
            )
        results["result"] = cloud.list_resources(type_name, identifier)

    if state in ("describe", "get"):
        if "read" not in handlers:
            module.exit_json(
                **results, msg=f"Resource type {type_name} cannot be read."
            )
        results["result"] = cloud.get_resource(type_name, identifier)

    if state == "present":
        results = cloud.present(
            type_name, identifier, params_to_set, create_only_params
        )

    if state == "absent":
        results["changed"] |= cloud.absent(type_name, identifier)

    module.exit_json(**results)


if __name__ == "__main__":
    main()
