#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2022, Ansible Project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# template: header.j2
# This module is autogenerated using the ansible.content_builder.
# See: https://github.com/ansible-community/ansible.content_builder


DOCUMENTATION = r"""
module: dynamodb_global_table
short_description: Creates and manages a Version 2019.11.21 global table
description:
- Creates and manages a Version 2019.11.21 global table.
- This resource cannot be used to create or manage a Version 2017.11.29 global table.
options:
    attribute_definitions:
        aliases:
        - AttributeDefinitions
        description:
        - Not Provived.
        elements: dict
        suboptions:
            attribute_name:
                aliases:
                - AttributeName
                description:
                - Not Provived.
                type: str
            attribute_type:
                aliases:
                - AttributeType
                description:
                - Not Provived.
                type: str
        type: list
    billing_mode:
        aliases:
        - BillingMode
        description:
        - Not Provived.
        type: str
    force:
        default: false
        description:
        - Cancel IN_PROGRESS and PENDING resource requestes.
        - Because you can only perform a single operation on a given resource at a
            time, there might be cases where you need to cancel the current resource
            operation to make the resource available so that another operation may
            be performed on it.
        type: bool
    global_secondary_indexes:
        aliases:
        - GlobalSecondaryIndexes
        description:
        - Not Provived.
        elements: dict
        suboptions:
            index_name:
                aliases:
                - IndexName
                description:
                - Not Provived.
                type: str
            key_schema:
                aliases:
                - KeySchema
                description:
                - Not Provived.
                elements: dict
                suboptions:
                    attribute_name:
                        aliases:
                        - AttributeName
                        description:
                        - Not Provived.
                        type: str
                    key_type:
                        aliases:
                        - KeyType
                        description:
                        - Not Provived.
                        type: str
                type: list
            projection:
                aliases:
                - Projection
                description:
                - Not Provived.
                suboptions:
                    non_key_attributes:
                        aliases:
                        - NonKeyAttributes
                        description:
                        - Not Provived.
                        elements: str
                        type: list
                    projection_type:
                        aliases:
                        - ProjectionType
                        description:
                        - Not Provived.
                        type: str
                type: dict
            write_provisioned_throughput_settings:
                aliases:
                - WriteProvisionedThroughputSettings
                description:
                - Not Provived.
                suboptions:
                    write_capacity_auto_scaling_settings:
                        aliases:
                        - WriteCapacityAutoScalingSettings
                        description:
                        - Not Provived.
                        suboptions:
                            max_capacity:
                                aliases:
                                - MaxCapacity
                                description:
                                - Not Provived.
                                type: int
                            min_capacity:
                                aliases:
                                - MinCapacity
                                description:
                                - Not Provived.
                                type: int
                            seed_capacity:
                                aliases:
                                - SeedCapacity
                                description:
                                - Not Provived.
                                type: int
                            target_tracking_scaling_policy_configuration:
                                aliases:
                                - TargetTrackingScalingPolicyConfiguration
                                description:
                                - Not Provived.
                                suboptions:
                                    disable_scale_in:
                                        aliases:
                                        - DisableScaleIn
                                        description:
                                        - Not Provived.
                                        type: bool
                                    scale_in_cooldown:
                                        aliases:
                                        - ScaleInCooldown
                                        description:
                                        - Not Provived.
                                        type: int
                                    scale_out_cooldown:
                                        aliases:
                                        - ScaleOutCooldown
                                        description:
                                        - Not Provived.
                                        type: int
                                    target_value:
                                        aliases:
                                        - TargetValue
                                        description:
                                        - Not Provived.
                                        type: int
                                type: dict
                        type: dict
                type: dict
        type: list
    key_schema:
        aliases:
        - KeySchema
        description:
        - Not Provived.
        elements: dict
        suboptions:
            attribute_name:
                aliases:
                - AttributeName
                description:
                - Not Provived.
                type: str
            key_type:
                aliases:
                - KeyType
                description:
                - Not Provived.
                type: str
        type: list
    local_secondary_indexes:
        aliases:
        - LocalSecondaryIndexes
        description:
        - Not Provived.
        elements: dict
        suboptions:
            index_name:
                aliases:
                - IndexName
                description:
                - Not Provived.
                type: str
            key_schema:
                aliases:
                - KeySchema
                description:
                - Not Provived.
                elements: dict
                suboptions:
                    attribute_name:
                        aliases:
                        - AttributeName
                        description:
                        - Not Provived.
                        type: str
                    key_type:
                        aliases:
                        - KeyType
                        description:
                        - Not Provived.
                        type: str
                type: list
            projection:
                aliases:
                - Projection
                description:
                - Not Provived.
                suboptions:
                    non_key_attributes:
                        aliases:
                        - NonKeyAttributes
                        description:
                        - Not Provived.
                        elements: str
                        type: list
                    projection_type:
                        aliases:
                        - ProjectionType
                        description:
                        - Not Provived.
                        type: str
                type: dict
        type: list
    replicas:
        aliases:
        - Replicas
        description:
        - Not Provived.
        elements: dict
        suboptions:
            contributor_insights_specification:
                aliases:
                - ContributorInsightsSpecification
                description:
                - Not Provived.
                suboptions:
                    enabled:
                        aliases:
                        - Enabled
                        description:
                        - Not Provived.
                        type: bool
                type: dict
            deletion_protection_enabled:
                aliases:
                - DeletionProtectionEnabled
                description:
                - Not Provived.
                type: bool
            global_secondary_indexes:
                aliases:
                - GlobalSecondaryIndexes
                description:
                - Not Provived.
                elements: dict
                suboptions:
                    contributor_insights_specification:
                        aliases:
                        - ContributorInsightsSpecification
                        description:
                        - Not Provived.
                        suboptions:
                            enabled:
                                aliases:
                                - Enabled
                                description:
                                - Not Provived.
                                type: bool
                        type: dict
                    index_name:
                        aliases:
                        - IndexName
                        description:
                        - Not Provived.
                        type: str
                    read_provisioned_throughput_settings:
                        aliases:
                        - ReadProvisionedThroughputSettings
                        description:
                        - Not Provived.
                        suboptions:
                            read_capacity_auto_scaling_settings:
                                aliases:
                                - ReadCapacityAutoScalingSettings
                                description:
                                - Not Provived.
                                suboptions:
                                    max_capacity:
                                        aliases:
                                        - MaxCapacity
                                        description:
                                        - Not Provived.
                                        type: int
                                    min_capacity:
                                        aliases:
                                        - MinCapacity
                                        description:
                                        - Not Provived.
                                        type: int
                                    seed_capacity:
                                        aliases:
                                        - SeedCapacity
                                        description:
                                        - Not Provived.
                                        type: int
                                    target_tracking_scaling_policy_configuration:
                                        aliases:
                                        - TargetTrackingScalingPolicyConfiguration
                                        description:
                                        - Not Provived.
                                        suboptions:
                                            disable_scale_in:
                                                aliases:
                                                - DisableScaleIn
                                                description:
                                                - Not Provived.
                                                type: bool
                                            scale_in_cooldown:
                                                aliases:
                                                - ScaleInCooldown
                                                description:
                                                - Not Provived.
                                                type: int
                                            scale_out_cooldown:
                                                aliases:
                                                - ScaleOutCooldown
                                                description:
                                                - Not Provived.
                                                type: int
                                            target_value:
                                                aliases:
                                                - TargetValue
                                                description:
                                                - Not Provived.
                                                type: int
                                        type: dict
                                type: dict
                            read_capacity_units:
                                aliases:
                                - ReadCapacityUnits
                                description:
                                - Not Provived.
                                type: int
                        type: dict
                type: list
            kinesis_stream_specification:
                aliases:
                - KinesisStreamSpecification
                description:
                - Not Provived.
                suboptions:
                    stream_arn:
                        aliases:
                        - StreamArn
                        description:
                        - Not Provived.
                        type: str
                type: dict
            point_in_time_recovery_specification:
                aliases:
                - PointInTimeRecoverySpecification
                description:
                - Not Provived.
                suboptions:
                    point_in_time_recovery_enabled:
                        aliases:
                        - PointInTimeRecoveryEnabled
                        description:
                        - Not Provived.
                        type: bool
                type: dict
            read_provisioned_throughput_settings:
                aliases:
                - ReadProvisionedThroughputSettings
                description:
                - Not Provived.
                suboptions:
                    read_capacity_auto_scaling_settings:
                        aliases:
                        - ReadCapacityAutoScalingSettings
                        description:
                        - Not Provived.
                        suboptions:
                            max_capacity:
                                aliases:
                                - MaxCapacity
                                description:
                                - Not Provived.
                                type: int
                            min_capacity:
                                aliases:
                                - MinCapacity
                                description:
                                - Not Provived.
                                type: int
                            seed_capacity:
                                aliases:
                                - SeedCapacity
                                description:
                                - Not Provived.
                                type: int
                            target_tracking_scaling_policy_configuration:
                                aliases:
                                - TargetTrackingScalingPolicyConfiguration
                                description:
                                - Not Provived.
                                suboptions:
                                    disable_scale_in:
                                        aliases:
                                        - DisableScaleIn
                                        description:
                                        - Not Provived.
                                        type: bool
                                    scale_in_cooldown:
                                        aliases:
                                        - ScaleInCooldown
                                        description:
                                        - Not Provived.
                                        type: int
                                    scale_out_cooldown:
                                        aliases:
                                        - ScaleOutCooldown
                                        description:
                                        - Not Provived.
                                        type: int
                                    target_value:
                                        aliases:
                                        - TargetValue
                                        description:
                                        - Not Provived.
                                        type: int
                                type: dict
                        type: dict
                    read_capacity_units:
                        aliases:
                        - ReadCapacityUnits
                        description:
                        - Not Provived.
                        type: int
                type: dict
            region:
                aliases:
                - Region
                description:
                - Not Provived.
                type: str
            sse_specification:
                aliases:
                - SSESpecification
                description:
                - Not Provived.
                suboptions:
                    kms_master_key_id:
                        aliases:
                        - KMSMasterKeyId
                        description:
                        - Not Provived.
                        type: str
                type: dict
            table_class:
                aliases:
                - TableClass
                description:
                - Not Provived.
                type: str
            tags:
                aliases:
                - Tags
                description:
                - Not Provived.
                elements: dict
                suboptions:
                    key:
                        aliases:
                        - Key
                        description:
                        - Not Provived.
                        type: str
                    value:
                        aliases:
                        - Value
                        description:
                        - Not Provived.
                        type: str
                type: list
        type: list
    sse_specification:
        aliases:
        - SSESpecification
        description:
        - Not Provived.
        suboptions:
            sse_enabled:
                aliases:
                - SSEEnabled
                description:
                - Not Provived.
                type: bool
            sse_type:
                aliases:
                - SSEType
                description:
                - Not Provived.
                type: str
        type: dict
    state:
        choices:
        - present
        - absent
        - list
        - describe
        - get
        default: present
        description:
        - Goal state for resource.
        - I(state=present) creates the resource if it doesn't exist, or updates to
            the provided state if the resource already exists.
        - I(state=absent) ensures an existing instance is deleted.
        - I(state=list) get all the existing resources.
        - I(state=describe) or I(state=get) retrieves information on an existing resource.
        type: str
    stream_specification:
        aliases:
        - StreamSpecification
        description:
        - Not Provived.
        suboptions:
            stream_view_type:
                aliases:
                - StreamViewType
                description:
                - Not Provived.
                type: str
        type: dict
    table_name:
        aliases:
        - TableName
        description:
        - Not Provived.
        type: str
    time_to_live_specification:
        aliases:
        - TimeToLiveSpecification
        description:
        - Not Provived.
        suboptions:
            attribute_name:
                aliases:
                - AttributeName
                description:
                - Not Provived.
                type: str
            enabled:
                aliases:
                - Enabled
                description:
                - Not Provived.
                type: bool
        type: dict
    wait:
        default: false
        description:
        - Wait for operation to complete before returning.
        type: bool
    wait_timeout:
        default: 320
        description:
        - How many seconds to wait for an operation to complete before timing out.
        type: int
    write_provisioned_throughput_settings:
        aliases:
        - WriteProvisionedThroughputSettings
        description:
        - Not Provived.
        suboptions:
            write_capacity_auto_scaling_settings:
                aliases:
                - WriteCapacityAutoScalingSettings
                description:
                - Not Provived.
                suboptions:
                    max_capacity:
                        aliases:
                        - MaxCapacity
                        description:
                        - Not Provived.
                        type: int
                    min_capacity:
                        aliases:
                        - MinCapacity
                        description:
                        - Not Provived.
                        type: int
                    seed_capacity:
                        aliases:
                        - SeedCapacity
                        description:
                        - Not Provived.
                        type: int
                    target_tracking_scaling_policy_configuration:
                        aliases:
                        - TargetTrackingScalingPolicyConfiguration
                        description:
                        - Not Provived.
                        suboptions:
                            disable_scale_in:
                                aliases:
                                - DisableScaleIn
                                description:
                                - Not Provived.
                                type: bool
                            scale_in_cooldown:
                                aliases:
                                - ScaleInCooldown
                                description:
                                - Not Provived.
                                type: int
                            scale_out_cooldown:
                                aliases:
                                - ScaleOutCooldown
                                description:
                                - Not Provived.
                                type: int
                            target_value:
                                aliases:
                                - TargetValue
                                description:
                                - Not Provived.
                                type: int
                        type: dict
                type: dict
        type: dict
author: Ansible Cloud Team (@ansible-collections)
version_added: 0.2.0
extends_documentation_fragment:
- amazon.aws.aws
- amazon.aws.ec2
- amazon.cloud.boto3
"""

EXAMPLES = r"""
"""

RETURN = r"""
result:
    description:
        - When I(state=list), it is a list containing dictionaries of resource information.
        - Otherwise, it is a dictionary of resource information.
        - When I(state=absent), it is an empty dictionary.
    returned: always
    type: complex
    contains:
        identifier:
            description: The unique identifier of the resource.
            type: str
        properties:
            description: The resource properties.
            type: dict
"""


from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    AnsibleAmazonCloudModule,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    CloudControlResource,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    ansible_dict_to_boto3_tag_list,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    scrub_none_parameters,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import map_key_to_alias


def main():
    argument_spec = dict(
        state=dict(
            type="str",
            choices=["present", "absent", "list", "describe", "get"],
            default="present",
        ),
    )

    argument_spec["attribute_definitions"] = {
        "type": "list",
        "elements": "dict",
        "options": {
            "attribute_name": {"type": "str", "aliases": ["AttributeName"]},
            "attribute_type": {"type": "str", "aliases": ["AttributeType"]},
        },
        "aliases": ["AttributeDefinitions"],
    }
    argument_spec["billing_mode"] = {"type": "str", "aliases": ["BillingMode"]}
    argument_spec["global_secondary_indexes"] = {
        "type": "list",
        "elements": "dict",
        "options": {
            "index_name": {"type": "str", "aliases": ["IndexName"]},
            "key_schema": {
                "type": "list",
                "elements": "dict",
                "options": {
                    "attribute_name": {"type": "str", "aliases": ["AttributeName"]},
                    "key_type": {"type": "str", "aliases": ["KeyType"]},
                },
                "aliases": ["KeySchema"],
            },
            "projection": {
                "type": "dict",
                "options": {
                    "non_key_attributes": {
                        "type": "list",
                        "elements": "str",
                        "aliases": ["NonKeyAttributes"],
                    },
                    "projection_type": {"type": "str", "aliases": ["ProjectionType"]},
                },
                "aliases": ["Projection"],
            },
            "write_provisioned_throughput_settings": {
                "type": "dict",
                "options": {
                    "write_capacity_auto_scaling_settings": {
                        "type": "dict",
                        "options": {
                            "min_capacity": {"type": "int", "aliases": ["MinCapacity"]},
                            "max_capacity": {"type": "int", "aliases": ["MaxCapacity"]},
                            "seed_capacity": {
                                "type": "int",
                                "aliases": ["SeedCapacity"],
                            },
                            "target_tracking_scaling_policy_configuration": {
                                "type": "dict",
                                "options": {
                                    "disable_scale_in": {
                                        "type": "bool",
                                        "aliases": ["DisableScaleIn"],
                                    },
                                    "scale_in_cooldown": {
                                        "type": "int",
                                        "aliases": ["ScaleInCooldown"],
                                    },
                                    "scale_out_cooldown": {
                                        "type": "int",
                                        "aliases": ["ScaleOutCooldown"],
                                    },
                                    "target_value": {
                                        "type": "int",
                                        "aliases": ["TargetValue"],
                                    },
                                },
                                "aliases": ["TargetTrackingScalingPolicyConfiguration"],
                            },
                        },
                        "aliases": ["WriteCapacityAutoScalingSettings"],
                    }
                },
                "aliases": ["WriteProvisionedThroughputSettings"],
            },
        },
        "aliases": ["GlobalSecondaryIndexes"],
    }
    argument_spec["key_schema"] = {
        "type": "list",
        "elements": "dict",
        "options": {
            "attribute_name": {"type": "str", "aliases": ["AttributeName"]},
            "key_type": {"type": "str", "aliases": ["KeyType"]},
        },
        "aliases": ["KeySchema"],
    }
    argument_spec["local_secondary_indexes"] = {
        "type": "list",
        "elements": "dict",
        "options": {
            "index_name": {"type": "str", "aliases": ["IndexName"]},
            "key_schema": {
                "type": "list",
                "elements": "dict",
                "options": {
                    "attribute_name": {"type": "str", "aliases": ["AttributeName"]},
                    "key_type": {"type": "str", "aliases": ["KeyType"]},
                },
                "aliases": ["KeySchema"],
            },
            "projection": {
                "type": "dict",
                "options": {
                    "non_key_attributes": {
                        "type": "list",
                        "elements": "str",
                        "aliases": ["NonKeyAttributes"],
                    },
                    "projection_type": {"type": "str", "aliases": ["ProjectionType"]},
                },
                "aliases": ["Projection"],
            },
        },
        "aliases": ["LocalSecondaryIndexes"],
    }
    argument_spec["write_provisioned_throughput_settings"] = {
        "type": "dict",
        "options": {
            "write_capacity_auto_scaling_settings": {
                "type": "dict",
                "options": {
                    "min_capacity": {"type": "int", "aliases": ["MinCapacity"]},
                    "max_capacity": {"type": "int", "aliases": ["MaxCapacity"]},
                    "seed_capacity": {"type": "int", "aliases": ["SeedCapacity"]},
                    "target_tracking_scaling_policy_configuration": {
                        "type": "dict",
                        "options": {
                            "disable_scale_in": {
                                "type": "bool",
                                "aliases": ["DisableScaleIn"],
                            },
                            "scale_in_cooldown": {
                                "type": "int",
                                "aliases": ["ScaleInCooldown"],
                            },
                            "scale_out_cooldown": {
                                "type": "int",
                                "aliases": ["ScaleOutCooldown"],
                            },
                            "target_value": {"type": "int", "aliases": ["TargetValue"]},
                        },
                        "aliases": ["TargetTrackingScalingPolicyConfiguration"],
                    },
                },
                "aliases": ["WriteCapacityAutoScalingSettings"],
            }
        },
        "aliases": ["WriteProvisionedThroughputSettings"],
    }
    argument_spec["replicas"] = {
        "type": "list",
        "elements": "dict",
        "options": {
            "region": {"type": "str", "aliases": ["Region"]},
            "global_secondary_indexes": {
                "type": "list",
                "elements": "dict",
                "options": {
                    "index_name": {"type": "str", "aliases": ["IndexName"]},
                    "contributor_insights_specification": {
                        "type": "dict",
                        "options": {
                            "enabled": {"type": "bool", "aliases": ["Enabled"]}
                        },
                        "aliases": ["ContributorInsightsSpecification"],
                    },
                    "read_provisioned_throughput_settings": {
                        "type": "dict",
                        "options": {
                            "read_capacity_units": {
                                "type": "int",
                                "aliases": ["ReadCapacityUnits"],
                            },
                            "read_capacity_auto_scaling_settings": {
                                "type": "dict",
                                "options": {
                                    "min_capacity": {
                                        "type": "int",
                                        "aliases": ["MinCapacity"],
                                    },
                                    "max_capacity": {
                                        "type": "int",
                                        "aliases": ["MaxCapacity"],
                                    },
                                    "seed_capacity": {
                                        "type": "int",
                                        "aliases": ["SeedCapacity"],
                                    },
                                    "target_tracking_scaling_policy_configuration": {
                                        "type": "dict",
                                        "options": {
                                            "disable_scale_in": {
                                                "type": "bool",
                                                "aliases": ["DisableScaleIn"],
                                            },
                                            "scale_in_cooldown": {
                                                "type": "int",
                                                "aliases": ["ScaleInCooldown"],
                                            },
                                            "scale_out_cooldown": {
                                                "type": "int",
                                                "aliases": ["ScaleOutCooldown"],
                                            },
                                            "target_value": {
                                                "type": "int",
                                                "aliases": ["TargetValue"],
                                            },
                                        },
                                        "aliases": [
                                            "TargetTrackingScalingPolicyConfiguration"
                                        ],
                                    },
                                },
                                "aliases": ["ReadCapacityAutoScalingSettings"],
                            },
                        },
                        "aliases": ["ReadProvisionedThroughputSettings"],
                    },
                },
                "aliases": ["GlobalSecondaryIndexes"],
            },
            "contributor_insights_specification": {
                "type": "dict",
                "options": {"enabled": {"type": "bool", "aliases": ["Enabled"]}},
                "aliases": ["ContributorInsightsSpecification"],
            },
            "point_in_time_recovery_specification": {
                "type": "dict",
                "options": {
                    "point_in_time_recovery_enabled": {
                        "type": "bool",
                        "aliases": ["PointInTimeRecoveryEnabled"],
                    }
                },
                "aliases": ["PointInTimeRecoverySpecification"],
            },
            "table_class": {"type": "str", "aliases": ["TableClass"]},
            "deletion_protection_enabled": {
                "type": "bool",
                "aliases": ["DeletionProtectionEnabled"],
            },
            "sse_specification": {
                "type": "dict",
                "options": {
                    "kms_master_key_id": {"type": "str", "aliases": ["KMSMasterKeyId"]}
                },
                "aliases": ["SSESpecification"],
            },
            "tags": {
                "type": "list",
                "elements": "dict",
                "options": {
                    "key": {"type": "str", "aliases": ["Key"]},
                    "value": {"type": "str", "aliases": ["Value"]},
                },
                "aliases": ["Tags"],
            },
            "read_provisioned_throughput_settings": {
                "type": "dict",
                "options": {
                    "read_capacity_units": {
                        "type": "int",
                        "aliases": ["ReadCapacityUnits"],
                    },
                    "read_capacity_auto_scaling_settings": {
                        "type": "dict",
                        "options": {
                            "min_capacity": {"type": "int", "aliases": ["MinCapacity"]},
                            "max_capacity": {"type": "int", "aliases": ["MaxCapacity"]},
                            "seed_capacity": {
                                "type": "int",
                                "aliases": ["SeedCapacity"],
                            },
                            "target_tracking_scaling_policy_configuration": {
                                "type": "dict",
                                "options": {
                                    "disable_scale_in": {
                                        "type": "bool",
                                        "aliases": ["DisableScaleIn"],
                                    },
                                    "scale_in_cooldown": {
                                        "type": "int",
                                        "aliases": ["ScaleInCooldown"],
                                    },
                                    "scale_out_cooldown": {
                                        "type": "int",
                                        "aliases": ["ScaleOutCooldown"],
                                    },
                                    "target_value": {
                                        "type": "int",
                                        "aliases": ["TargetValue"],
                                    },
                                },
                                "aliases": ["TargetTrackingScalingPolicyConfiguration"],
                            },
                        },
                        "aliases": ["ReadCapacityAutoScalingSettings"],
                    },
                },
                "aliases": ["ReadProvisionedThroughputSettings"],
            },
            "kinesis_stream_specification": {
                "type": "dict",
                "options": {"stream_arn": {"type": "str", "aliases": ["StreamArn"]}},
                "aliases": ["KinesisStreamSpecification"],
            },
        },
        "aliases": ["Replicas"],
    }
    argument_spec["sse_specification"] = {
        "type": "dict",
        "options": {
            "sse_enabled": {"type": "bool", "aliases": ["SSEEnabled"]},
            "sse_type": {"type": "str", "aliases": ["SSEType"]},
        },
        "aliases": ["SSESpecification"],
    }
    argument_spec["stream_specification"] = {
        "type": "dict",
        "options": {"stream_view_type": {"type": "str", "aliases": ["StreamViewType"]}},
        "aliases": ["StreamSpecification"],
    }
    argument_spec["table_name"] = {"type": "str", "aliases": ["TableName"]}
    argument_spec["time_to_live_specification"] = {
        "type": "dict",
        "options": {
            "attribute_name": {"type": "str", "aliases": ["AttributeName"]},
            "enabled": {"type": "bool", "aliases": ["Enabled"]},
        },
        "aliases": ["TimeToLiveSpecification"],
    }
    argument_spec["state"] = {
        "type": "str",
        "choices": ["present", "absent", "list", "describe", "get"],
        "default": "present",
    }
    argument_spec["wait"] = {"type": "bool", "default": False}
    argument_spec["wait_timeout"] = {"type": "int", "default": 320}
    argument_spec["force"] = {"type": "bool", "default": False}

    required_if = [
        [
            "state",
            "present",
            ["replicas", "table_name", "attribute_definitions", "key_schema"],
            True,
        ],
        ["state", "absent", ["table_name"], True],
        ["state", "get", ["table_name"], True],
    ]
    mutually_exclusive = []

    module = AnsibleAmazonCloudModule(
        argument_spec=argument_spec,
        required_if=required_if,
        mutually_exclusive=mutually_exclusive,
        supports_check_mode=True,
    )
    cloud = CloudControlResource(module)

    type_name = "AWS::DynamoDB::GlobalTable"

    params = {}

    params["attribute_definitions"] = module.params.get("attribute_definitions")
    params["billing_mode"] = module.params.get("billing_mode")
    params["global_secondary_indexes"] = module.params.get("global_secondary_indexes")
    params["key_schema"] = module.params.get("key_schema")
    params["local_secondary_indexes"] = module.params.get("local_secondary_indexes")
    params["replicas"] = module.params.get("replicas")
    params["sse_specification"] = module.params.get("sse_specification")
    params["stream_specification"] = module.params.get("stream_specification")
    params["table_name"] = module.params.get("table_name")
    params["time_to_live_specification"] = module.params.get(
        "time_to_live_specification"
    )
    params["write_provisioned_throughput_settings"] = module.params.get(
        "write_provisioned_throughput_settings"
    )

    # The DesiredState we pass to AWS must be a JSONArray of non-null values
    _params_to_set = scrub_none_parameters(params)

    # Only if resource is taggable
    if module.params.get("tags") is not None:
        _params_to_set["tags"] = ansible_dict_to_boto3_tag_list(module.params["tags"])

    # Use the alias from argument_spec as key and avoid snake_to_camel conversions
    params_to_set = map_key_to_alias(_params_to_set, argument_spec)

    # Ignore createOnlyProperties that can be set only during resource creation
    create_only_params = [
        "/properties/LocalSecondaryIndexes",
        "/properties/TableName",
        "/properties/KeySchema",
    ]

    # Necessary to handle when module does not support all the states
    handlers = ["create", "read", "update", "delete", "list"]

    state = module.params.get("state")
    identifier = ["/properties/TableName"]

    results = {"changed": False, "result": {}}

    if state == "list":
        if "list" not in handlers:
            module.exit_json(
                **results, msg=f"Resource type {type_name} cannot be listed."
            )
        results["result"] = cloud.list_resources(type_name, identifier)

    if state in ("describe", "get"):
        if "read" not in handlers:
            module.exit_json(
                **results, msg=f"Resource type {type_name} cannot be read."
            )
        results["result"] = cloud.get_resource(type_name, identifier)

    if state == "present":
        results = cloud.present(
            type_name, identifier, params_to_set, create_only_params
        )

    if state == "absent":
        results["changed"] |= cloud.absent(type_name, identifier)

    module.exit_json(**results)


if __name__ == "__main__":
    main()
