#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2022, Ansible Project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# template: header.j2
# This module is autogenerated using the ansible.content_builder.
# See: https://github.com/ansible-community/ansible.content_builder


DOCUMENTATION = r"""
module: rds_custom_db_engine_version
short_description: Creates and manages a custom DB engine version (CEV)
description:
- Creates and manages a custom DB engine version (CEV). For more information, see
    U(https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-customdbengineversion.html)
options:
    database_installation_files_s3_bucket_name:
        aliases:
        - DatabaseInstallationFilesS3BucketName
        description:
        - The name of an Amazon S3 bucket that contains database installation files
            for your CEV. For example, a valid bucket name is my-custom-installation-files.
        type: str
    database_installation_files_s3_prefix:
        aliases:
        - DatabaseInstallationFilesS3Prefix
        description:
        - The Amazon S3 directory that contains the database installation files for
            your CEV. For example, a valid bucket name is 123456789012/cev1.
        - If this setting isnt specified, no prefix is assumed.
        type: str
    description:
        aliases:
        - Description
        description:
        - An optional description of your CEV.
        type: str
    engine:
        aliases:
        - Engine
        description:
        - The database engine to use for your custom engine version (CEV). The only
            supported value is custom-oracle-ee.
        type: str
    engine_version:
        aliases:
        - EngineVersion
        description:
        - The name of your CEV. The name format is 19.customized_string .
        - For example, a valid name is 19.my_cev1.
        - This setting is required for RDS Custom for Oracle, but optional for Amazon
            RDS. The combination of Engine and EngineVersion is unique per customer
            per Region.
        type: str
    force:
        default: false
        description:
        - Cancel IN_PROGRESS and PENDING resource requestes.
        - Because you can only perform a single operation on a given resource at a
            time, there might be cases where you need to cancel the current resource
            operation to make the resource available so that another operation may
            be performed on it.
        type: bool
    identifier:
        description:
        - For compound primary identifiers, to specify the primary identifier as a
            string, list each in the order that they are specified in the identifier
            list definition, separated by '|'.
        - For more details, visit U(https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/resource-identifier.html).
        type: str
    kms_key_id:
        aliases:
        - KMSKeyId
        description:
        - The AWS KMS key identifier for an encrypted CEV. A symmetric KMS key is
            required for RDS Custom, but optional for Amazon RDS.
        type: str
    manifest:
        aliases:
        - Manifest
        description:
        - The CEV manifest, which is a JSON document that describes the installation
            .zip files stored in Amazon S3. Specify the name/value pairs in a file
            or a quoted string.
        - RDS Custom applies the patches in the order in which they are listed.
        type: str
    purge_tags:
        default: true
        description:
        - Remove tags not listed in I(tags).
        type: bool
    state:
        choices:
        - present
        - absent
        - list
        - describe
        - get
        default: present
        description:
        - Goal state for resource.
        - I(state=present) creates the resource if it doesn't exist, or updates to
            the provided state if the resource already exists.
        - I(state=absent) ensures an existing instance is deleted.
        - I(state=list) get all the existing resources.
        - I(state=describe) or I(state=get) retrieves information on an existing resource.
        type: str
    status:
        aliases:
        - Status
        choices:
        - available
        - inactive
        - inactive-except-restore
        default: available
        description:
        - The availability status to be assigned to the CEV.
        type: str
    tags:
        aliases:
        - Tags
        - resource_tags
        description:
        - A dict of tags to apply to the resource.
        - To remove all tags set I(tags={}) and I(purge_tags=true).
        type: dict
    wait:
        default: false
        description:
        - Wait for operation to complete before returning.
        type: bool
    wait_timeout:
        default: 320
        description:
        - How many seconds to wait for an operation to complete before timing out.
        type: int
author: Ansible Cloud Team (@ansible-collections)
version_added: 0.3.0
extends_documentation_fragment:
- amazon.aws.aws
- amazon.aws.ec2
- amazon.cloud.boto3
"""

EXAMPLES = r"""
"""

RETURN = r"""
result:
    description:
        - When I(state=list), it is a list containing dictionaries of resource information.
        - Otherwise, it is a dictionary of resource information.
        - When I(state=absent), it is an empty dictionary.
    returned: always
    type: complex
    contains:
        identifier:
            description: The unique identifier of the resource.
            type: str
        properties:
            description: The resource properties.
            type: dict
"""


from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    AnsibleAmazonCloudModule,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    CloudControlResource,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    ansible_dict_to_boto3_tag_list,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    scrub_none_parameters,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import map_key_to_alias


def main():
    argument_spec = dict(
        state=dict(
            type="str",
            choices=["present", "absent", "list", "describe", "get"],
            default="present",
        ),
    )

    argument_spec["database_installation_files_s3_bucket_name"] = {
        "type": "str",
        "aliases": ["DatabaseInstallationFilesS3BucketName"],
    }
    argument_spec["database_installation_files_s3_prefix"] = {
        "type": "str",
        "aliases": ["DatabaseInstallationFilesS3Prefix"],
    }
    argument_spec["description"] = {"type": "str", "aliases": ["Description"]}
    argument_spec["engine"] = {"type": "str", "aliases": ["Engine"]}
    argument_spec["engine_version"] = {"type": "str", "aliases": ["EngineVersion"]}
    argument_spec["kms_key_id"] = {"type": "str", "aliases": ["KMSKeyId"]}
    argument_spec["manifest"] = {"type": "str", "aliases": ["Manifest"]}
    argument_spec["status"] = {
        "type": "str",
        "default": "available",
        "choices": ["available", "inactive", "inactive-except-restore"],
        "aliases": ["Status"],
    }
    argument_spec["tags"] = {"type": "dict", "aliases": ["Tags", "resource_tags"]}
    argument_spec["state"] = {
        "type": "str",
        "choices": ["present", "absent", "list", "describe", "get"],
        "default": "present",
    }
    argument_spec["wait"] = {"type": "bool", "default": False}
    argument_spec["wait_timeout"] = {"type": "int", "default": 320}
    argument_spec["force"] = {"type": "bool", "default": False}
    argument_spec["purge_tags"] = {"type": "bool", "default": True}
    argument_spec["identifier"] = {"type": "str"}

    required_if = [
        ["state", "list", ["engine"], True],
        [
            "state",
            "present",
            [
                "engine_version",
                "database_installation_files_s3_bucket_name",
                "identifier",
                "engine",
            ],
            True,
        ],
        ["state", "absent", ["engine", "engine_version", "identifier"], True],
        ["state", "get", ["engine", "engine_version", "identifier"], True],
    ]
    mutually_exclusive = [[("engine", "engine_version"), "identifier"]]

    module = AnsibleAmazonCloudModule(
        argument_spec=argument_spec,
        required_if=required_if,
        mutually_exclusive=mutually_exclusive,
        supports_check_mode=True,
    )
    cloud = CloudControlResource(module)

    type_name = "AWS::RDS::CustomDBEngineVersion"

    params = {}

    params["database_installation_files_s3_bucket_name"] = module.params.get(
        "database_installation_files_s3_bucket_name"
    )
    params["database_installation_files_s3_prefix"] = module.params.get(
        "database_installation_files_s3_prefix"
    )
    params["description"] = module.params.get("description")
    params["engine"] = module.params.get("engine")
    params["engine_version"] = module.params.get("engine_version")
    params["identifier"] = module.params.get("identifier")
    params["kms_key_id"] = module.params.get("kms_key_id")
    params["manifest"] = module.params.get("manifest")
    params["status"] = module.params.get("status")
    params["tags"] = module.params.get("tags")

    # The DesiredState we pass to AWS must be a JSONArray of non-null values
    _params_to_set = scrub_none_parameters(params)

    # Only if resource is taggable
    if module.params.get("tags") is not None:
        _params_to_set["tags"] = ansible_dict_to_boto3_tag_list(module.params["tags"])

    # Use the alias from argument_spec as key and avoid snake_to_camel conversions
    params_to_set = map_key_to_alias(_params_to_set, argument_spec)

    # Ignore createOnlyProperties that can be set only during resource creation
    create_only_params = [
        "/properties/Engine",
        "/properties/EngineVersion",
        "/properties/DatabaseInstallationFilesS3BucketName",
        "/properties/DatabaseInstallationFilesS3Prefix",
        "/properties/KMSKeyId",
        "/properties/Manifest",
    ]

    # Necessary to handle when module does not support all the states
    handlers = ["create", "read", "update", "delete", "list"]

    state = module.params.get("state")
    identifier = ["/properties/Engine", "/properties/EngineVersion"]
    if (
        state in ("present", "absent", "get", "describe")
        and module.params.get("identifier") is None
    ):
        if not module.params.get("engine") or not module.params.get("engine_version"):
            module.fail_json(
                "You must specify all the ('engine', 'engine_version') identifiers."
            )

    results = {"changed": False, "result": {}}

    if state == "list":
        if "list" not in handlers:
            module.exit_json(
                **results, msg=f"Resource type {type_name} cannot be listed."
            )
        results["result"] = cloud.list_resources(type_name, identifier)

    if state in ("describe", "get"):
        if "read" not in handlers:
            module.exit_json(
                **results, msg=f"Resource type {type_name} cannot be read."
            )
        results["result"] = cloud.get_resource(type_name, identifier)

    if state == "present":
        results = cloud.present(
            type_name, identifier, params_to_set, create_only_params
        )

    if state == "absent":
        results["changed"] |= cloud.absent(type_name, identifier)

    module.exit_json(**results)


if __name__ == "__main__":
    main()
