#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2022, Ansible Project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# template: header.j2
# This module is autogenerated by amazon_cloud_code_generator.
# See: https://github.com/ansible-collections/amazon_cloud_code_generator

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
module: s3_access_point
short_description: Create and manage Amazon S3 access points to use to access S3 buckets
description: Create and manage Amazon S3 access points to use to access S3 buckets
    (list, create, update, describe, delete).
options:
    bucket:
        description:
        - The name of the bucket that you want to associate this Access Point with.
        required: true
        type: str
    name:
        description:
        - The name you want to assign to this Access Point.
        - If you dont specify a name, AWS CloudFormation generates a unique ID and
            uses that ID for the access point name.
        type: str
    policy:
        description:
        - The Access Point Policy you want to apply to this access point.
        type: dict
    policy_status:
        description:
        - Not Provived.
        suboptions:
            is_public:
                choices:
                - 'false'
                - 'true'
                description:
                - Specifies whether the policy is public or not.
                type: str
        type: dict
    public_access_block_configuration:
        description:
        - The I(public_access_block) configuration that you want to apply to this
            Access Point.
        - You can enable the configuration options in any combination.
        - For more information about when Amazon S3 considers a bucket or object public,
            see U(https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html#access-control-block-public-access-policy-status)
            The Meaning of Public in the Amazon Simple Storage Service Developer Guide.
        suboptions:
            block_public_acls:
                description:
                - Specifies whether Amazon S3 should block public access control lists
                    (ACLs) for buckets in this account.
                - 'Setting this element to C(True) causes the following behavior:'
                - '- PUT Bucket acl and PUT Object acl calls fail if the specified
                    ACL is public.'
                - '- PUT Object calls fail if the request includes a public ACL.'
                - . - PUT Bucket calls fail if the request includes a public ACL.
                - Enabling this setting doesnt affect existing policies or ACLs.
                type: bool
            block_public_policy:
                description:
                - Specifies whether Amazon S3 should block public bucket policies
                    for buckets in this account.
                - Setting this element to C(True) causes Amazon S3 to reject calls
                    to PUT Bucket policy if the specified bucket policy allows public
                    access.
                - Enabling this setting doesnt affect existing bucket policies.
                type: bool
            ignore_public_acls:
                description:
                - Specifies whether Amazon S3 should ignore public ACLs for buckets
                    in this account.
                - Setting this element to C(True) causes Amazon S3 to ignore all public
                    ACLs on buckets in this account and any objects that they contain.
                - Enabling this setting doesnt affect the persistence of any existing
                    ACLs and doesnt prevent new public ACLs from being set.
                type: bool
            restrict_public_buckets:
                description:
                - Specifies whether Amazon S3 should restrict public bucket policies
                    for this bucket.
                - Setting this element to C(True) restricts access to this bucket
                    to only AWS services and authorized users within this account
                    if the bucket has a public policy.
                - Enabling this setting doesnt affect previously stored bucket policies,
                    except that public and cross-account access within any public
                    bucket policy, including non-public delegation to specific accounts,
                    is blocked.
                type: bool
        type: dict
    state:
        choices:
        - present
        - absent
        - list
        - describe
        - get
        default: present
        description:
        - Goal state for resource.
        - I(state=present) creates the resource if it doesn't exist, or updates to
            the provided state if the resource already exists.
        - I(state=absent) ensures an existing instance is deleted.
        - I(state=list) get all the existing resources.
        - I(state=describe) or I(state=get) retrieves information on an existing resource.
        type: str
    vpc_configuration:
        description:
        - If you include this field, Amazon S3 restricts access to this Access Point
            to requests from the specified Virtual Private Cloud (VPC).The Virtual
            Private Cloud (VPC) configuration for a bucket access point.
        suboptions:
            vpc_id:
                description:
                - If this field is specified, this access point will only allow connections
                    from the specified VPC ID.
                type: str
        type: dict
    wait:
        default: false
        description:
        - Wait for operation to complete before returning.
        type: bool
    wait_timeout:
        default: 320
        description:
        - How many seconds to wait for an operation to complete before timing out.
        type: int
author: Ansible Cloud Team (@ansible-collections)
version_added: 0.1.0
requirements: []
extends_documentation_fragment:
- amazon.aws.aws
- amazon.aws.ec2
"""

EXAMPLES = r"""
"""

RETURN = r"""
result:
    description: Dictionary containing resource information.
    returned: always
    type: complex
    contains:
        identifier:
            description: The unique identifier of the resource.
            type: str
        properties:
            description: The resource properties.
            type: dict
"""

import json

from ansible_collections.amazon.aws.plugins.module_utils.core import AnsibleAWSModule
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    CloudControlResource,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    snake_dict_to_camel_dict,
)
from ansible_collections.amazon.cloud.plugins.module_utils.core import (
    ansible_dict_to_boto3_tag_list,
)


def main():

    argument_spec = dict(
        state=dict(
            type="str",
            choices=["present", "absent", "list", "describe", "get"],
            default="present",
        ),
    )

    argument_spec["name"] = {"type": "str"}
    argument_spec["bucket"] = {"type": "str", "required": True}
    argument_spec["vpc_configuration"] = {
        "type": "dict",
        "options": {"vpc_id": {"type": "str"}},
    }
    argument_spec["public_access_block_configuration"] = {
        "type": "dict",
        "options": {
            "block_public_acls": {"type": "bool"},
            "ignore_public_acls": {"type": "bool"},
            "block_public_policy": {"type": "bool"},
            "restrict_public_buckets": {"type": "bool"},
        },
    }
    argument_spec["policy"] = {"type": "dict"}
    argument_spec["policy_status"] = {
        "type": "dict",
        "options": {"is_public": {"type": "str", "choices": ["false", "true"]}},
    }
    argument_spec["state"] = {
        "type": "str",
        "choices": ["present", "absent", "list", "describe", "get"],
        "default": "present",
    }
    argument_spec["wait"] = {"type": "bool", "default": False}
    argument_spec["wait_timeout"] = {"type": "int", "default": 320}

    required_if = [
        ["state", "present", ["bucket"], True],
        ["state", "absent", [], True],
        ["state", "get", [], True],
    ]

    module = AnsibleAWSModule(
        argument_spec=argument_spec, required_if=required_if, supports_check_mode=True
    )
    cloud = CloudControlResource(module)

    type_name = "AWS::S3::AccessPoint"

    params = {}

    params["bucket"] = module.params.get("bucket")
    params["name"] = module.params.get("name")
    params["policy"] = module.params.get("policy")
    params["policy_status"] = module.params.get("policy_status")
    params["public_access_block_configuration"] = module.params.get(
        "public_access_block_configuration"
    )
    params["vpc_configuration"] = module.params.get("vpc_configuration")

    # The DesiredState we pass to AWS must be a JSONArray of non-null values
    _params_to_set = {k: v for k, v in params.items() if v is not None}

    # Only if resource is taggable
    if module.params.get("tags", None):
        _params_to_set["tags"] = ansible_dict_to_boto3_tag_list(module.params["tags"])

    params_to_set = snake_dict_to_camel_dict(_params_to_set, capitalize_first=True)

    # Ignore createOnlyProperties that can be set only during resource creation
    create_only_params = [
        "name",
        "bucket",
        "vpc_configuration",
        "public_access_block_configuration",
    ]

    state = module.params.get("state")
    identifier = module.params.get("name")

    results = {"changed": False, "result": []}

    if state == "list":
        results["result"] = cloud.list_resources(type_name)

    if state in ("describe", "get"):
        results["result"] = cloud.get_resource(type_name, identifier)

    if state == "present":
        results["changed"] |= cloud.present(
            type_name, identifier, params_to_set, create_only_params
        )
        results["result"] = cloud.get_resource(type_name, identifier)

    if state == "absent":
        results["changed"] |= cloud.absent(type_name, identifier)

    module.exit_json(**results)


if __name__ == "__main__":
    main()
