name: integration

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - stable-*

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      ansible_version: milestone
      python_version: "3.12"
    steps:
      - name: Create AWS/sts session credentials
        uses: ansible/ansible-test-auth@v1

      - name: Run integration tests
        uses: ansible-community/ansible-test-gh-action@d3a8ec7a59694e25e210fcd44738910149537f0e
        with:
          ansible-core-version: ${{ env.ansible_version }}
          origin-python-version: ${{ env.python_version }}
          testing-type: integration
          test-deps: >-
            git+https://github.com/ansible-collections/amazon.aws.git,main
            git+https://github.com/ansible-collections/community.aws.git,main
            community.crypto
          pre-test-cmd: python -m pip install -r tests/integration/constraints.txt -r tests/integration/requirements.txt
